version: "3"
services:
    app:
        image: hyper_python:latest
        build: python
        environment:
          - PORT=8080
        depends_on:
          - "redis"

    redis:
        image: hyper_redis:latest
        build: redis
