apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: hyper-redis
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: hyper_redis:latest
